#!/usr/bin/env python3
"""Generates STATUS.md — one-page dashboard of every project in MANIFEST.yaml.

Reads each project's path on disk and reports:
  - has .git?        (if not — bootstrap not yet run)
  - has origin?      (if not — bootstrap not yet pushed)
  - current branch
  - uncommitted file count
  - last commit (date + subject)
  - has CI workflow?  has loadtest workflow?
  - has artifacts/samples?
  - size on disk (after .gitignore)
"""
from __future__ import annotations
import datetime as dt
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _manifest import HUB, projects  # type: ignore


def sh(args: list[str], cwd: Path) -> str:
    try:
        out = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        return ""


def du_human(path: Path) -> str:
    out = sh(["du", "-sh", str(path)], path.parent if path.parent.exists() else Path("/"))
    return out.split()[0] if out else "?"


def main() -> None:
    rows = []
    summary = {"total": 0, "with_git": 0, "with_origin": 0, "dirty": 0, "with_ci": 0}

    for p in projects():
        summary["total"] += 1
        path = Path(p["path"])
        exists = path.is_dir()
        has_git = exists and (path / ".git").is_dir()
        if has_git:
            summary["with_git"] += 1

        branch = remote = last_commit = ""
        dirty_count = 0
        if has_git:
            branch = sh(["git", "symbolic-ref", "--short", "HEAD"], path) or "?"
            remote = sh(["git", "remote", "get-url", "origin"], path)
            if remote:
                summary["with_origin"] += 1
            dirty_count = len([l for l in sh(["git", "status", "--porcelain"], path).splitlines() if l])
            if dirty_count:
                summary["dirty"] += 1
            last_commit = sh(["git", "log", "-1", "--format=%cs · %s"], path)

        has_ci = exists and (path / ".github" / "workflows" / "ci.yml").exists()
        has_loadtest = exists and (path / ".github" / "workflows" / "loadtest.yml").exists()
        has_artifacts = exists and (path / "artifacts" / "samples").exists()
        if has_ci:
            summary["with_ci"] += 1

        size = du_human(path) if exists else "—"

        rows.append({
            "repo": p["repo"],
            "kind": p["kind"],
            "stack": p["stack"],
            "wave": p.get("audit_wave", "—"),
            "slo": p.get("slo_passed", "—"),
            "exists": "✓" if exists else "✗",
            "git": "✓" if has_git else "✗",
            "origin": "✓" if remote else "✗",
            "branch": branch or "—",
            "dirty": str(dirty_count) if dirty_count else "—",
            "last": last_commit[:60] if last_commit else "—",
            "ci": "✓" if has_ci else "✗",
            "load": "✓" if has_loadtest else "—",
            "art": "✓" if has_artifacts else "✗",
            "size": size,
        })

    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    out = [
        f"# Portfolio status — {now}",
        "",
        f"**Manifest:** [`MANIFEST.yaml`](MANIFEST.yaml) — {summary['total']} projects",
        "",
        "## Headline",
        "",
        f"- {summary['with_git']}/{summary['total']} have local git",
        f"- {summary['with_origin']}/{summary['total']} have a GitHub remote (origin set)",
        f"- {summary['with_ci']}/{summary['total']} have CI workflow installed",
        f"- {summary['dirty']}/{summary['total']} have uncommitted local work",
        "",
        "## Per-project state",
        "",
        "| Repo | Kind | Stack | Wave | SLO | Exists | Git | Origin | Branch | Dirty | Last commit | CI | Load | Art | Size |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| `{r['repo']}` | {r['kind']} | {r['stack']} | {r['wave']} | {r['slo']} | "
            f"{r['exists']} | {r['git']} | {r['origin']} | {r['branch']} | {r['dirty']} | "
            f"{r['last']} | {r['ci']} | {r['load']} | {r['art']} | {r['size']} |"
        )
    out += [
        "",
        "## Legend",
        "",
        "- **Wave** — audit wave (1/2/3) from `AUDIT_REPORT.md` + `COMPLETION_REPORT.md`",
        "- **SLO** — `yes` / `no` / `near` / `mixed` from measured load tests in `COMPLETION_REPORT.md`",
        "- **Dirty** — count of uncommitted files",
        "- **CI / Load / Art** — `.github/workflows/ci.yml`, `loadtest.yml`, `artifacts/samples/` present?",
        "",
        f"Generated by [`scripts/status.py`](scripts/status.py) at {now}.",
        "",
    ]

    target = HUB / "STATUS.md"
    target.write_text("\n".join(out))
    print(f"wrote {target} — {summary['total']} projects, {summary['with_origin']} with remote, {summary['dirty']} dirty")


if __name__ == "__main__":
    main()
